# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-05 11:25
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=256, verbose_name='Last Name')),
                ('uid', models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Id Number')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Points')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('draft', 'Draft')], default='new', max_length=32, verbose_name='Status')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Create Datetime')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='Update Datetime')),
                ('clerk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='pos.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='pos.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('upc', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='UPC')),
                ('part_number', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Part Number')),
                ('reorder_limit', models.PositiveIntegerField(default=0, verbose_name='Re-order Limit')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Purchase Price')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='pos.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set([('order', 'product')]),
        ),
    ]
