# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-09 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20170208_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.TextField(max_length=1024, verbose_name='Description', null=True, blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='pos.Unit'),
        ),
    ]
