# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-12-11 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_customer_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='points',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='customer',
            name='needs_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Needs Account Balance'),
        ),
        migrations.AddField(
            model_name='customer',
            name='want_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Want Account Balance'),
        ),
        migrations.AddField(
            model_name='order',
            name='needs_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price(Needs)'),
        ),
        migrations.AddField(
            model_name='order',
            name='needs_total_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity(Needs)'),
        ),
        migrations.AddField(
            model_name='order',
            name='want_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price(Want)'),
        ),
        migrations.AddField(
            model_name='order',
            name='want_total_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity(Want)'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('needs', 'Needs'), ('want', 'Want')], default='needs', max_length=8, verbose_name='Type'),
        ),
    ]
